export const EXPENSE_TYPE_INCOME = "Income";
export const EXPENSE_TYPE_EXPENSE = "Expense";
export const EXPENSE_TYPE_IGNORE = "Ignore";
export const EXPENSE_TYPE_TRANSFER_INTERNAL = "Transfer Internal";
export const EXPENSE_TYPE_TRANSFER_EXTERNAL = "Transfer External";

export const ACCOUNT_TYPE_CHECKING = "Checking Account";
export const ACCOUNT_TYPE_SAVING = "Saving Account";
export const ACCOUNT_TYPE_CREDIT_CARD = "Credit Card";
export const ACCOUNT_TYPE_HOME_LOAN = "Home Loan";
export const ACCOUNT_TYPE_VEHICLE_LOAN = "Vehicle Loan";

export const FIELD_TYPE_DATE = "date";
export const FIELD_TYPE_STRING = "string";
export const FIELD_TYPE_AMOUNT = "amount";
export const FIELD_TYPE_DATE_TIME = "dateTime";

export const EXPENSE_FIELD_NONE = "none";
export const EXPENSE_FIELD_DATE = "date";
export const EXPENSE_FIELD_DESCRIPTION = "description";
export const EXPENSE_FIELD_AMOUNT = "amount";

export const EXPENSE_TYPE_COND_EXPENSE_IF_GT_0_EL_INCOME =
  "EXPENSE_IF_GT_0_EL_INCOME";
export const EXPENSE_TYPE_COND_INCOME_IF_GT_0_EL_EXPENSE =
  "INCOME_IF_GT_0_EL_EXPENSE";
export const EXPENSE_TYPE_COND_EXPENSE_IF_GT_0 = "EXPENSE_IF_GT_0";
export const EXPENSE_TYPE_COND_INCOME_IF_GT_0 = "INCOME_IF_GT_0";

export const EXPENSE_TYPES = [
  EXPENSE_TYPE_INCOME,
  EXPENSE_TYPE_EXPENSE,
  EXPENSE_TYPE_IGNORE,
  EXPENSE_TYPE_TRANSFER_INTERNAL,
  EXPENSE_TYPE_TRANSFER_EXTERNAL,
];

export const ACCOUNT_TYPES = [
  ACCOUNT_TYPE_CHECKING,
  ACCOUNT_TYPE_SAVING,
  ACCOUNT_TYPE_CREDIT_CARD,
  ACCOUNT_TYPE_HOME_LOAN,
  ACCOUNT_TYPE_VEHICLE_LOAN,
];

export const FIELD_TYPES = [
  FIELD_TYPE_DATE,
  FIELD_TYPE_STRING,
  FIELD_TYPE_AMOUNT,
  FIELD_TYPE_DATE_TIME,
];

export const EXPENSE_FIELDS = [
  EXPENSE_FIELD_NONE,
  EXPENSE_FIELD_DATE,
  EXPENSE_FIELD_DESCRIPTION,
  EXPENSE_FIELD_AMOUNT,
];

export const EXPENSE_TYPE_COND = [
  "",
  EXPENSE_TYPE_COND_EXPENSE_IF_GT_0,
  EXPENSE_TYPE_COND_INCOME_IF_GT_0,
  EXPENSE_TYPE_COND_EXPENSE_IF_GT_0_EL_INCOME,
  EXPENSE_TYPE_COND_INCOME_IF_GT_0_EL_EXPENSE,
];
