export const EXPENSE_TYPE_INCOME = "Income";
export const EXPENSE_TYPE_EXPENSE = "Expense";
export const EXPENSE_TYPE_IGNORE = "Ignore";
export const EXPENSE_TYPE_TRANSFER_INTERNAL = "Transfer Internal";
export const EXPENSE_TYPE_TRANSFER_EXTERNAL = "Transfer External";
export const ACCOUNT_TYPE_CHECKING = "Checking Account";
export const ACCOUNT_TYPE_SAVING = "Saving Account";
export const ACCOUNT_TYPE_CREDIT_CARD = "Credit Card";
export const ACCOUNT_TYPE_HOME_LOAN = "Home Loan";
export const ACCOUNT_TYPE_VEHICLE_LOAN = "Vehicle Loan";

export const EXPENSE_TYPES = [
  EXPENSE_TYPE_INCOME,
  EXPENSE_TYPE_EXPENSE,
  EXPENSE_TYPE_IGNORE,
  EXPENSE_TYPE_TRANSFER_INTERNAL,
  EXPENSE_TYPE_TRANSFER_EXTERNAL,
];

export const ACCOUNT_TYPES = [
  ACCOUNT_TYPE_CHECKING,
  ACCOUNT_TYPE_SAVING,
  ACCOUNT_TYPE_CREDIT_CARD,
  ACCOUNT_TYPE_HOME_LOAN,
  ACCOUNT_TYPE_VEHICLE_LOAN,
];
